This is makeindex, version 2.15 [TeX Live 2012] (kpathsea + Thai support).
Scanning style file ./dissertation.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file dissertation.acn.....done (1084 entries accepted, 0 rejected).
Sorting entries............done (12353 comparisons).
Generating output file dissertation.acr....done (321 lines written, 0 warnings).
Output written in dissertation.acr.
Transcript written in dissertation.alg.
